version: "3.9"
   
services:
  jupyter:
    build:
      image: 936189880821.dkr.ecr.us-west-2.amazonaws.com/getty-jupyter-notebooks:1.0
    ports:
      - "8080:8080"
    volumes:
      - ./notebooks:/home/jovyan/
    env_file: 
      - .env.base
      - .env

    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
