version: "3.9"
   
services:
  jupyter:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXUS_USER=${NEXUS_USER}
        - NEXUS_PASSWORD=${NEXUS_PASSWORD}
    ports:
      - "80:80"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - /mnt/or-stg-task-management-worker-data:/data-staging
    env_file: 
      - .env.base
      - .env

    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
